name: ci
on:
  push:
    branches:
      # Match SemVer major release branches
      # e.g. "12.x" or "8.x"
      - '[0-9]+.x'
      - 'main'
      - 'next'
      - 'next-major'
      - 'beta'
      - 'alpha'
  pull_request: {}
permissions:
  actions: write #  to cancel/stop running workflows (styfle/cancel-workflow-action)
  contents: read #  to fetch code (actions/checkout)

jobs:
  main:
    strategy:
      fail-fast: false
      matrix:
        node: [18]
        pnpm: ['7.12.x']
    runs-on: ubuntu-latest
    steps:
      - name: 🛑 Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.0

      - name: ⬇️ Checkout repo
        uses: actions/checkout@v2

      - name: ⎔ Setup pnpm ${{ matrix.pnpm }}
        uses: pnpm/action-setup@v2
        with:
          version: ${{ matrix.pnpm }}

      - name: ⎔ Setup Node ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          cache: 'pnpm'
          node-version: ${{ matrix.node }}
          registry-url: 'https://npm.pkg.github.com'

      - name: 📥 Download deps
        run: pnpm install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GPR_TOKEN }}

      - name: 🏗 Build
        run: pnpm build

      - name: 🔍 Verify types
        run: pnpm type-check

      - name: 💅 Verify format (`pnpm format` committed?)
        run: pnpm format --check --no-write

      - name: 🕵️ Lint
        run: pnpm lint

      - name: 🛡️ Test
        run: pnpm test
